[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200 

[functions."cleanup-games"]
  schedule = "*/30 * * * *" # 30 mins
  
[functions."update-ip-list"]
  schedule = "0 0 * * *" # every day
  timeout = 900

[functions."deploy-succeeded"]
  timeout = 900
