[[redirects]]
  from = "/debug"
  to = "/.netlify/functions/debug-redis"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200 

[functions."cleanup-games"]
  schedule = "*/30 * * * *" # 30 mins
  
[functions."update-ip-list"]
  schedule = "0 0 * * *" # every day
