name: Cleanup Stale Games

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  trigger-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Cleanup Endpoint
        run: |
          curl --request GET \
          --url 'https://envy-sooty.vercel.app/api/run-cleanup' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
