name: Cleanup Stale Games


on:
  schedule:
    # 3. Set the schedule to run every 30 minutes using a cron expression
    - cron: '*/30 * * * *'
  
  workflow_dispatch:


jobs:

  trigger-cleanup:

    runs-on: ubuntu-latest


    steps:
      - name: Trigger Vercel Cleanup Endpoint
        run: |
          curl --request GET \
          --url 'https://envy-xi.vercel.app/api/run-cleanup' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
